print("Please enter required details of Employee")
print()
name = input('Enter name of the Employee: ')
employeeId = int(input('Enter Employee ID:'))
age = int(input('Enter age of the Employee: '))
salary = float(input('Enter salary of Employee: '))
address = input('Enter Address of Employee: ')
married = input('Married or not? [True|False]')
print()
print('Please confirm your details')
print('name of the employee is: ',name)
print('Employee id:',employeeId)
print('Employee age:',age)
print('Employee salary: ',salary)
print('Address of Employee:',address)
print('Marital Status of employee: ',married)
